# Generated by Django 2.0.3 on 2018-04-16 23:44

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0010_auto_20180417_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madeDate', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DUE', 'DUE'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCEPTED'), ('CANCELLED', 'CANCELLED')], max_length=12)),
                ('comments', models.TextField(blank=True)),
                ('rejectedReasons', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momentOfCreation', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spamWords', models.TextField(default='pennis, viagra, jes extender, cialis')),
                ('defaultCountry', models.CharField(default='+34', max_length=4)),
                ('tax', models.DecimalField(decimal_places=1, default=1.21, max_digits=3)),
                ('timeResultsCached', models.PositiveSmallIntegerField(default=24)),
                ('maxResults', models.PositiveSmallIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.URLField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('curriculum', models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='EndorserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True)),
                ('curriculum', models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Finder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=12)),
                ('minimumPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('maximumPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lastUse', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('systemFolder', models.BooleanField(default=False)),
                ('parentFolder', models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='LegalText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=2)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentDate', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=12)),
                ('body', models.CharField(max_length=12)),
                ('priority', models.CharField(choices=[('HIGH', 'HIGH'), ('NEUTRAL', 'NEUTRAL'), ('LOW', 'LOW')], max_length=12)),
                ('folder', models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='MiscellaneousRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.URLField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('curriculum', models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momentOfCreation', models.DateTimeField(auto_now_add=True)),
                ('reply', models.CharField(blank=True, max_length=240)),
                ('momentOfReply', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(blank=True, max_length=12, verbose_name='phone number')),
                ('curriculum', models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.URLField(blank=True)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialIdentities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditCard', models.ForeignKey(on_delete='SET_NULL', to='AcmeExplorer.CreditCard')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurvivalClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationMoment', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TagValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=12, unique=True)),
                ('requirements', models.TextField(blank=True)),
                ('cancelationReasons', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Category')),
                ('legalText', models.ForeignKey(on_delete='PROTECT', to='AcmeExplorer.LegalText')),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('actor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AcmeExplorer.Actor')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('AcmeExplorer.actor',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('actor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AcmeExplorer.Actor')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('AcmeExplorer.actor',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Explorer',
            fields=[
                ('actor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AcmeExplorer.Actor')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('AcmeExplorer.actor',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('actor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AcmeExplorer.Actor')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('AcmeExplorer.actor',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ranger',
            fields=[
                ('actor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AcmeExplorer.Actor')),
                ('trip', models.ForeignKey(on_delete='PROTECT', to='AcmeExplorer.Trip')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('AcmeExplorer.actor',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('actor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AcmeExplorer.Actor')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('AcmeExplorer.actor',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='tagvalue',
            name='trip',
            field=models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Trip'),
        ),
        migrations.AddField(
            model_name='survivalclass',
            name='trip',
            field=models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Trip'),
        ),
        migrations.AddField(
            model_name='story',
            name='trip',
            field=models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Trip'),
        ),
        migrations.AddField(
            model_name='stage',
            name='trip',
            field=models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Trip'),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='trip',
            field=models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Trip'),
        ),
        migrations.AddField(
            model_name='socialidentities',
            name='user',
            field=models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Actor'),
        ),
        migrations.AddField(
            model_name='note',
            name='trip',
            field=models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Trip'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiverUser',
            field=models.ForeignKey(on_delete='CASCADE', related_name='receiverUser', to='AcmeExplorer.Actor'),
        ),
        migrations.AddField(
            model_name='message',
            name='senderUser',
            field=models.ForeignKey(on_delete='CASCADE', related_name='senderUser', to='AcmeExplorer.Actor'),
        ),
        migrations.AddField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Actor'),
        ),
        migrations.AddField(
            model_name='finder',
            name='results',
            field=models.ManyToManyField(to='AcmeExplorer.Trip'),
        ),
        migrations.AddField(
            model_name='audit',
            name='trip',
            field=models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Trip'),
        ),
        migrations.AddField(
            model_name='application',
            name='creditCard',
            field=models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.CreditCard'),
        ),
        migrations.AddField(
            model_name='application',
            name='trip',
            field=models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Trip'),
        ),
        migrations.AddField(
            model_name='survivalclass',
            name='manager',
            field=models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Manager'),
        ),
        migrations.AddField(
            model_name='story',
            name='explorer',
            field=models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Explorer'),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='sponsor',
            field=models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Sponsor'),
        ),
        migrations.AddField(
            model_name='note',
            name='auditor',
            field=models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Auditor'),
        ),
        migrations.AddField(
            model_name='finder',
            name='explorer',
            field=models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Explorer'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='ranger',
            field=models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Ranger'),
        ),
        migrations.AddField(
            model_name='contact',
            name='explorer',
            field=models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Explorer'),
        ),
        migrations.AddField(
            model_name='audit',
            name='auditor',
            field=models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Auditor'),
        ),
        migrations.AddField(
            model_name='application',
            name='explorer',
            field=models.ForeignKey(on_delete='CASCADE', to='AcmeExplorer.Explorer'),
        ),
    ]
