# Generated by Django 2.0.4 on 2018-04-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcmeExplorer', '0002_legaltext_draftmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='address',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='actor',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
