# Generated by Django 2.0.4 on 2018-04-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcmeExplorer', '0004_auto_20180421_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parentFolder',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='AcmeExplorer.Folder'),
        ),
    ]
