# Generated by Django 2.0.4 on 2018-04-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcmeExplorer', '0006_auto_20180421_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parentFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='AcmeExplorer.Folder'),
        ),
    ]
