# Generated by Django 2.0.4 on 2018-05-03 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcmeExplorer', '0008_auto_20180503_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categories',
            new_name='parentCategory',
        ),
    ]
