# Generated by Django 2.0.4 on 2018-05-03 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AcmeExplorer', '0011_auto_20180503_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='creditCard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.CreditCard'),
        ),
        migrations.AlterField(
            model_name='application',
            name='explorer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Explorer'),
        ),
        migrations.AlterField(
            model_name='application',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Trip'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='auditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Auditor'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Trip'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parentCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Category'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='explorer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Explorer'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='ranger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Ranger'),
        ),
        migrations.AlterField(
            model_name='educationalrecord',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Curriculum'),
        ),
        migrations.AlterField(
            model_name='endorserrecord',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Curriculum'),
        ),
        migrations.AlterField(
            model_name='finder',
            name='explorer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Explorer'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Actor'),
        ),
        migrations.AlterField(
            model_name='message',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Folder'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiverUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiverUser', to='AcmeExplorer.Actor'),
        ),
        migrations.AlterField(
            model_name='message',
            name='senderUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderUser', to='AcmeExplorer.Actor'),
        ),
        migrations.AlterField(
            model_name='miscellaneousrecord',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Curriculum'),
        ),
        migrations.AlterField(
            model_name='note',
            name='auditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Auditor'),
        ),
        migrations.AlterField(
            model_name='note',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Trip'),
        ),
        migrations.AlterField(
            model_name='personalrecord',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Curriculum'),
        ),
        migrations.AlterField(
            model_name='socialidentities',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Actor'),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Sponsor'),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Trip'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Trip'),
        ),
        migrations.AlterField(
            model_name='story',
            name='explorer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Explorer'),
        ),
        migrations.AlterField(
            model_name='story',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Trip'),
        ),
        migrations.AlterField(
            model_name='survivalclass',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Location'),
        ),
        migrations.AlterField(
            model_name='survivalclass',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Manager'),
        ),
        migrations.AlterField(
            model_name='survivalclass',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Trip'),
        ),
        migrations.AlterField(
            model_name='tagvalue',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Tag'),
        ),
        migrations.AlterField(
            model_name='tagvalue',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Category'),
        ),
    ]
