# Generated by Django 2.0.4 on 2018-05-05 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AcmeExplorer', '0012_auto_20180503_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalrecord',
            name='curriculum',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AcmeExplorer.Curriculum'),
            preserve_default=False,
        ),
    ]
