from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(Actor)
admin.site.register(Administrator)
admin.site.register(Auditor)
admin.site.register(Category)
admin.site.register(ConfigurationSystem)
admin.site.register(Folder)
admin.site.register(Contact)
admin.site.register(LegalText)
admin.site.register(Finder)
admin.site.register(Manager)
admin.site.register(Message)
admin.site.register(Audit)
admin.site.register(CreditCard)
admin.site.register(Location)
admin.site.register(EndorserRecord)
admin.site.register(MiscellaneousRecord)
admin.site.register(PersonalRecord)
admin.site.register(ProfessionalRecord)
admin.site.register(EducationalRecord)
admin.site.register(Application)
admin.site.register(Curriculum)
admin.site.register(Explorer)
admin.site.register(Note)
admin.site.register(Ranger)
admin.site.register(SocialIdentities)
admin.site.register(Sponsor)
admin.site.register(Sponsorship)
admin.site.register(Stage)
admin.site.register(Story)
admin.site.register(SurvivalClass)
admin.site.register(Tag)
admin.site.register(TagValue)
admin.site.register(Trip)